name: LamDeathPenalties
version: '${project.version}'
main: org.yusaki.lamDeathPenalties.LamDeathPenalties
api-version: '1.21'
folia-supported: true
depend: [YskLib]
softdepend: [PlaceholderAPI]

commands:
  lmdp:
    description: Manage soul points
    usage: /lmdp [set|give|check] [player] [amount]
    aliases: [dp, deathpenalties, soulpoints]

permissions:
  lmdp.check.others:
    description: Check other players' soul points
    default: op
  lmdp.admin:
    description: Admin commands for soul points
    default: op
  lmdp.bypass:
    description: Bypass all death penalties
    default: op
